### ISSUE TITLE
Fails to work on Mac OS X 10.9

### ISSUE THREAD

**Issue by matthewforr** [zsong/diffy#3]
This plugin isn't working on my machine. Looking into the ST2 console I see this error:

````
Reloading plugin /Users/matthew/Library/Application Support/Sublime Text 2/Packages/Diffy/diffy.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./diffy.py", line 3, in <module>
    from .diffy_lib import diffier
ValueError: Attempted relative import in non-package
````

**Comment by zsong** [comment]
Fixed. Please update to the latest version.
